version: '3.5'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
  
  # redis-server:
  #   image: "redis:alpine"
  #   command: redis-server
  #   ports:
  #     - "6379:6379"
